apiVersion: v1
kind: Service
metadata: 
  name: {{ .Values.name }}-service
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.labels }}
  ports:
  - name: {{ .Values.name }}-port
    port: 80
    targetPort: 8080